# Generated by Django 6.0.3 on 2026-03-30 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Igreja',
                'verbose_name_plural': 'Igrejas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='igreja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.igreja'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='igreja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.igreja'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='igreja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.igreja'),
        ),
        migrations.AddField(
            model_name='professor',
            name='igreja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.igreja'),
        ),
        migrations.AddField(
            model_name='turma',
            name='igreja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.igreja'),
        ),
    ]
