# Generated by Django 6.0.3 on 2026-03-26 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_monitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.aluno')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.nivel')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.professor')),
            ],
        ),
    ]
