# Generated by Django 6.0.3 on 2026-04-04 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('school', '0002_igreja_aluno_igreja_monitor_igreja_nivel_igreja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='igreja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='school.igreja'),
        ),
    ]
